@startuml
class logic.Building {
- ArrayList<EnterProfile> enterProfileList
- int populationCount
- int potentialInfectedCount
+ <<Create>> Building()
+ EnterProfile addProfile(Person,int)
+ EnterProfile removeProfile(int)
+ int getPopulationCount()
+ int getPotentialInfectedCount()
+ ArrayList<EnterProfile> getEnterProfileList()
}
class logic.EnterProfile {
~ Person person
~ int bodyTemperature
+ <<Create>> EnterProfile(Person,int)
+ Person getPerson()
+ int getBodyTemperature()
+ void setPerson(Person)
+ void setBodyTemperature(int)
+ boolean hasFever()
}
class logic.Person {
- String name
- int ID
+ <<Create>> Person(String,int)
+ String getName()
+ int getID()
+ void setName(String)
+ void setID(int)
}
@enduml