@startuml
class logic.components.Market {
- String name
- ArrayList<Food> marketFood
- ArrayList<Potion> marketpotion
+ String getName()
+ ArrayList<Food> getFoods()
+ ArrayList<Potion> getPotions()
+ void setName(String)
+ void setFoods(ArrayList<Food>)
+ void setPotions(ArrayList<Potion>)
}
class logic.components.Status {
- int hp
- int durable
- int attack
- int magic
+ int getHp()
+ int getDurability()
+ int getAttack()
+ int getMagic()
+ int getDurable()
+ void addStatus(Status)
+ void setHp(int)
+ void setDurability(int)
+ void setAttack(int)
+ void setMagic(int)
}
class logic.components.Potion {
- String name
- int price
- Status stat
+ String getName()
+ int getPrice()
+ Status getStat()
+ Status getIncreasingStatus()
+ void setName(String)
+ void setIncreasingStatus(Status)
+ void setPrice(int)
+ boolean equals(Object)
+ int hashCode()
}
class logic.game.GameController {
+ ArrayList<Market> markets
+ ArrayList<Player> players
+ ArrayList<Monster> monsters
+ ArrayList<Ore> ores
+ {static} GameController instance
+ boolean gameEnd
+ {static} GameController getInstance()
+ void addMarket(Market)
+ void addMonster(Monster)
+ void addPlayer(Player)
+ void endDay()
+ void removeDeadPlayerAndMonster()
+ boolean buyOre(int,int)
+ boolean checkGameEnd()
+ {static} Status createNewStatus(int,int,int,int)
}
class logic.components.Monster {
- String name
- Status stat
- Food dropfood
- Potion droppotion
+ void setFood(Food)
+ void setPotion(Potion)
+ Status getStatus()
+ String getName()
+ Food getFood()
+ Potion getPotion()
+ void attack(Player)
+ void magicAttack(Player)
+ void setStatus(Status)
+ void setName(String)
}
class logic.components.Food {
- String name
- int price
- int energy
+ String getName()
+ int getPrice()
+ int getEnergy()
+ void setName(String)
+ void setPrice(int)
+ boolean assertEquals(Food)
+ void setEnergy(int)
+ boolean equals(Object)
}
class logic.components.Player {
- String name
- Status stat
- int energy
- int money
~ ArrayList<Food> foods
~ ArrayList<Potion> potions
~ ArrayList<Ore> ores
+ Status getStatus()
+ String getName()
+ ArrayList<Ore> getOres()
+ boolean buyOre(Ore)
+ int getEnergy()
+ int getMoney()
+ ArrayList<Food> getFoods()
+ ArrayList<Potion> getPotions()
+ void setMoney(int)
+ void attack(Monster)
+ void magicAttack(Monster)
+ void drinkPotion(int)
+ void eatFood(int)
+ void sellPotion(int)
+ void sellFood(int)
+ void setStatus(Status)
+ void setName(String)
+ void setEnergy(int)
+ void setFoods(ArrayList<Food>)
+ void setPotions(ArrayList<Potion>)
+ void setOres(ArrayList<Ore>)
+ void daypass()
}
class logic.components.Ore {
- String name
- int cost
+ String getName()
+ int getPrice()
+ int getCost()
+ void setName(String)
+ void setCost(int)
+ boolean equals(Object)
+ int hashCode()
}
@enduml